# Change these first
owner: dongqw # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Bee Uptime
    url: https://uptime.tob.ee
  - name: Bee Auth
    url: https://auth.tob.ee
  - name: Bee Pass
    url: https://pass.tob.ee
  - name: Bee Docs
    url: https://docs.tob.ee
  - name: Bee S3
    url: https://s3.tob.ee
  - name: Bee Status
    url: https://status.tob.ee
  - name: Bee CDN
    url: https://cdn.tob.ee
  - name: Bee Portainer
    url: https://portainer.tob.ee
  - name: Bee Short URL
    url: https://tob.ee
  - name: Bee Subconverter
    url: $SUBCONVERTER_URL
  - name: AIA
    url: $AIA_URL

assignees: # Users to assign downtime issues (optional)
  - dongqw

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.tob.ee
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Bee Uptime
  theme: night
  # introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    # - title: GitHub
    #   href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
